In [1062]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
import pandas as pd

In [1064]:
df1=pd.read_csv('test_set_features.csv')
df2=pd.read_csv('training_set_features.csv')
df3=pd.read_csv('training_set_labels.csv')
df4=pd.read_csv('submission_format.csv')
df41=pd.read_csv('submission_format.csv')
df41

       respondent_id  h1n1_vaccine  seasonal_vaccine
0              26707           0.5               0.7
1              26708           0.5               0.7
2              26709           0.5               0.7
3              26710           0.5               0.7
4              26711           0.5               0.7
...              ...           ...               ...
26703          53410           0.5               0.7
26704          53411           0.5               0.7
26705          53412           0.5               0.7
26706          53413           0.5               0.7
26707          53414           0.5               0.7

[26708 rows x 3 columns]

In [1065]:
print(df1.shape)
print(df2.shape)
print(df3.shape)
print(df4.shape)

(26708, 36)
(26707, 36)
(26707, 3)
(26708, 3)

In [1068]:
df1.head(2)

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,"> $75,000",Not Married,Rent,Employed,mlyzmhmf,"MSA, Not Principle City",1.0,0.0,atmlpfrs,hfxkjkmi
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,Non-MSA,3.0,0.0,atmlpfrs,xqwwgdyp

In [1070]:
df2.head(2)

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe

In [1072]:
df3.head(2)

   respondent_id  xyz_vaccine  seasonal_vaccine
0              0            0                 0
1              1            0                 1

In [1074]:
df4.head(2)

   respondent_id  h1n1_vaccine  seasonal_vaccine
0          26707           0.5               0.7
1          26708           0.5               0.7

In [1076]:
df_train = pd.merge(df2, df3, on='respondent_id')
df_train

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation,xyz_vaccine,seasonal_vaccine
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN,0,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,...,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe,0,1
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo,0,0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN,0,1
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,Own,Not in Labor Force,qufhixun,Non-MSA,0.0,0.0,NaN,NaN,0,0
26703,26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,Rent,Employed,lzgpxyit,"MSA, Principle City",1.0,0.0,fcxhlnwr,cmhcxjea,0,0
26704,26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,...,Own,NaN,lzgpxyit,"MSA, Not Principle City",0.0,0.0,NaN,NaN,0,1
26705,26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,Rent,Employed,lrircsnp,Non-MSA,1.0,0.0,fcxhlnwr,haliazsg,0,0
26706,26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,Own,Not in Labor Force,mlyzmhmf,"MSA, Principle City",1.0,0.0,NaN,NaN,0,0

In [1078]:
features1=df_train[df_train.columns[1:-4]]
features1.drop('health_insurance',axis=1,inplace=True)

C:\Users\Shubham kumar soni\AppData\Local\Temp\ipykernel_25328\3425411427.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features1.drop('health_insurance',axis=1,inplace=True)

In [1080]:
df_train.employment_industry.value_counts()

employment_industry
fcxhlnwr    2468
wxleyezf    1804
ldnlellj    1231
pxcmvdjn    1037
atmlpfrs     926
arjwrbjb     871
xicduogh     851
mfikgejo     614
vjjrobsf     527
rucpziij     523
xqicxuve     511
saaquncn     338
cfqqtusy     325
nduyfdeo     286
mcubkhph     275
wlfvacwt     215
dotnnunm     201
haxffmxo     148
msuufmds     124
phxvnwax      89
qnlwzans      13
Name: count, dtype: int64

In [1082]:
def fill_nan_with_mode(df):
    for column in df.columns:
        if df[column].isnull().any(): 
            mode_value = df[column].mode()[0]  
            df[column].fillna(mode_value, inplace=True)

# Apply the function to fill NaN values in the DataFrame
fill_nan_with_mode(features1)

C:\Users\Shubham kumar soni\AppData\Local\Temp\ipykernel_25328\4212213808.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column].fillna(mode_value, inplace=True)

In [1084]:
features1.age_group.unique()

array(['55 - 64 Years', '35 - 44 Years', '18 - 34 Years', '65+ Years',
       '45 - 54 Years'], dtype=object)

In [1086]:
age_mapping = {
    '18 - 34 Years': 0,
    '35 - 44 Years': 1,
    '45 - 54 Years': 2,
    '55 - 64 Years': 3,
    '65+ Years': 4
}

# Apply the mapping to the DataFrame
features1['age_range_encoded'] = features1['age_group'].map(age_mapping)

C:\Users\Shubham kumar soni\AppData\Local\Temp\ipykernel_25328\1217092571.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features1['age_range_encoded'] = features1['age_group'].map(age_mapping)

In [1088]:
features1.education.unique()
# Define the mapping for educational levels to integer values
education_mapping = {
    '< 12 Years': 0,
    '12 Years': 1,
    'Some College': 2,
    'College Graduate': 3
}

# Apply the mapping to the 'education' column
features1['education_encoded'] = features1['education'].map(education_mapping)

C:\Users\Shubham kumar soni\AppData\Local\Temp\ipykernel_25328\2176915772.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features1['education_encoded'] = features1['education'].map(education_mapping)

In [1090]:
features1.race.unique()
# Define the mapping for race categories to integer values
race_mapping = {
    'White': 0,
    'Black': 1,
    'Other or Multiple': 2,
    'Hispanic': 3
}

# Apply the mapping to the 'race' column
features1['race_encoded'] = features1['race'].map(race_mapping)

C:\Users\Shubham kumar soni\AppData\Local\Temp\ipykernel_25328\3067986375.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features1['race_encoded'] = features1['race'].map(race_mapping)

In [1092]:
features1.sex.unique()
sex_mapping = {'Male': 1, 'Female': 0}

# Apply mapping to create a new 'sex_encoded' column
features1['sex_encoded'] = features1['sex'].map(sex_mapping)

C:\Users\Shubham kumar soni\AppData\Local\Temp\ipykernel_25328\1613907392.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features1['sex_encoded'] = features1['sex'].map(sex_mapping)

In [1094]:
features1.income_poverty.unique()
income_poverty_mapping = {
    'Below Poverty': 0,
    '<= $75,000, Above Poverty': 1,
    '> $75,000': 2
}

# Apply the mapping to the 'income_poverty' column
features1['income_poverty_encoded'] = features1['income_poverty'].map(income_poverty_mapping)

C:\Users\Shubham kumar soni\AppData\Local\Temp\ipykernel_25328\1616307936.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  features1['income_poverty_encoded'] = features1['income_poverty'].map(income_poverty_mapping)

In [1096]:
features1.marital_status.unique()
marital_status_mapping = {
    'Not Married': 0,
    'Married': 1
}

# Apply the mapping to the 'marital_status' column
features1['marital_status_encoded'] = features1['marital_status'].map(marital_status_mapping)

In [1098]:
features1.rent_or_own.unique()
rent_or_own_mapping = {
    'Own': 0,
    'Rent': 1
}

# Apply the mapping to the 'rent_or_own' column
features1['rent_or_own_encoded'] = features1['rent_or_own'].map(rent_or_own_mapping)

In [1100]:
features1.employment_status.unique()
employment_status_mapping = {
    'Not in Labor Force': 0,
    'Employed': 1,
    'Unemployed': 2
}

# Apply the mapping to the 'employment_status' column
features1['employment_status_encoded'] = features1['employment_status'].map(employment_status_mapping)

In [1102]:
features1.hhs_geo_region.unique()

array(['oxchjgsf', 'bhuqouqj', 'qufhixun', 'lrircsnp', 'atmpeygn',
       'lzgpxyit', 'fpwskwrf', 'mlyzmhmf', 'dqpwygqj', 'kbazzjca'],
      dtype=object)

In [1104]:
categories = {'oxchjgsf':0, 'bhuqouqj':1, 'qufhixun':2, 'lrircsnp':3, 'atmpeygn':4,
                       'lzgpxyit':5, 'fpwskwrf':6, 'mlyzmhmf':7, 'dqpwygqj':8, 'kbazzjca':9}


features1['hhs_geo_region_encoded'] = features1['hhs_geo_region'].map(categories)

In [1106]:
features1.census_msa.unique()
msa_map = {
    'Non-MSA': 0,
   'MSA, Not Principle  City' : 1,
    'MSA, Principle City': 2
}

# Map the categorical values to numerical codes
features1['census_msa_encoded'] = features1['census_msa'].map(msa_map)

In [1108]:
columns_to_drop = ['age_group', 'education', 'race', 'sex', 'income_poverty',
                   'marital_status', 'rent_or_own', 'employment_status',
                   'hhs_geo_region', 'census_msa']

# Create features2 by dropping the specified columns
features2 = features1.drop(columns=columns_to_drop)

In [1110]:
df12=df1.copy()
df12.columns

Index(['respondent_id', 'xyz_concern', 'xyz_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'age_group',
       'education', 'race', 'sex', 'income_poverty', 'marital_status',
       'rent_or_own', 'employment_status', 'hhs_geo_region', 'census_msa',
       'household_adults', 'household_children', 'employment_industry',
       'employment_occupation'],
      dtype='object')

In [1112]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Define the mappings for categorical variables to numerical codes
age_mapping = {
    '18 - 34 Years': 0,
    '35 - 44 Years': 1,
    '45 - 54 Years': 2,
    '55 - 64 Years': 3,
    '65+ Years': 4
}

education_mapping = {
    '< 12 Years': 0,
    '12 Years': 1,
    'Some College': 2,
    'College Graduate': 3
}

race_mapping = {
    'White': 0,
    'Black': 1,
    'Other or Multiple': 2,
    'Hispanic': 3
}

sex_mapping = {
    'Male': 1,
    'Female': 0
}

income_poverty_mapping = {
    'Below Poverty': 0,
    '<= $75,000, Above Poverty': 1,
    '> $75,000': 2
}

rent_or_own_mapping = {
    'Own': 0,
    'Rent': 1
}

employment_status_mapping = {
    'Not in Labor Force': 0,
    'Employed': 1,
    'Unemployed': 2
}
msa_map = {
    'Non-MSA': 0,
   'MSA, Not Principle  City' : 1,
    'MSA, Principle City': 2
}
marital_status_mapping = {
    'Not Married': 0,
    'Married': 1
}

categories = {'oxchjgsf':0, 'bhuqouqj':1, 'qufhixun':2, 'lrircsnp':3, 'atmpeygn':4,
                       'lzgpxyit':5, 'fpwskwrf':6, 'mlyzmhmf':7, 'dqpwygqj':8, 'kbazzjca':9}

# Apply the mappings to respective columns
df12['age_group_encoded'] = df12['age_group'].map(age_mapping)
df12['education_encoded'] = df12['education'].map(education_mapping)
df12['race_encoded'] = df12['race'].map(race_mapping)
df12['sex_encoded'] = df12['sex'].map(sex_mapping)
df12['income_poverty_encoded'] = df12['income_poverty'].map(income_poverty_mapping)
df12['rent_or_own_encoded'] = df12['rent_or_own'].map(rent_or_own_mapping)
df12['hhs_geo_region_encoded'] = df12['hhs_geo_region'].map(categories )
df12['employment_status_encoded'] = df12['employment_status'].map(employment_status_mapping)
df12['census_msa_encoded'] = df12['census_msa'].map(msa_map)
df12['marital_status_encoded'] = df12['marital_status'].map(marital_status_mapping)
df12.drop(columns=columns_to_drop,inplace=True)

In [1114]:
df12['age_range_encoded']=df12['age_group_encoded']
df12.columns

Index(['respondent_id', 'xyz_concern', 'xyz_knowledge',
       'behavioral_antiviral_meds', 'behavioral_avoidance',
       'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'health_insurance', 'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'household_adults',
       'household_children', 'employment_industry', 'employment_occupation',
       'age_group_encoded', 'education_encoded', 'race_encoded', 'sex_encoded',
       'income_poverty_encoded', 'rent_or_own_encoded',
       'hhs_geo_region_encoded', 'employment_status_encoded',
       'census_msa_encoded', 'marital_status_encoded', 'age_range_encoded'],
      dtype='object')

In [1116]:
def fill_nan_with_mode(df):
    for column in df.columns:
        if df[column].isnull().any(): 
            mode_value = df[column].mode()[0]
            df[column].fillna(mode_value, inplace=True)


fill_nan_with_mode(df12)

In [1118]:
df12.isnull().sum()

respondent_id                  0
xyz_concern                    0
xyz_knowledge                  0
behavioral_antiviral_meds      0
behavioral_avoidance           0
behavioral_face_mask           0
behavioral_wash_hands          0
behavioral_large_gatherings    0
behavioral_outside_home        0
behavioral_touch_face          0
doctor_recc_xyz                0
doctor_recc_seasonal           0
chronic_med_condition          0
child_under_6_months           0
health_worker                  0
health_insurance               0
opinion_xyz_vacc_effective     0
opinion_xyz_risk               0
opinion_xyz_sick_from_vacc     0
opinion_seas_vacc_effective    0
opinion_seas_risk              0
opinion_seas_sick_from_vacc    0
household_adults               0
household_children             0
employment_industry            0
employment_occupation          0
age_group_encoded              0
education_encoded              0
race_encoded                   0
sex_encoded                    0
income_poverty_encoded         0
rent_or_own_encoded            0
hhs_geo_region_encoded         0
employment_status_encoded      0
census_msa_encoded             0
marital_status_encoded         0
age_range_encoded              0
dtype: int64

In [1120]:
df_train1

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,sex_encoded,income_poverty_encoded,marital_status_encoded,rent_or_own_encoded,employment_status_encoded,hhs_geo_region_encoded,census_msa_encoded,xyz_vaccine,seasonal_vaccine,respondent_id
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1,0,0,1,1,1,1,0,1,1
2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,1,0,0,1,2,1,0,0,2
3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0,0,0,1,0,3,2,0,1,3
4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0,1,1,0,1,2,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,1,0,0,0,2,0,0,0,26702
26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1,1,0,1,1,5,2,0,0,26703
26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,...,0,1,0,0,1,5,1,0,1,26704
26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,1,1,1,1,3,0,0,0,26705
26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,1,1,0,0,7,2,0,0,26706

In [1122]:
df_train1=features2
df_train1['xyz_vaccine']=df_train['xyz_vaccine']
df_train1['seasonal_vaccine']=df_train['seasonal_vaccine']
df_train1['respondent_id']=df_train['respondent_id']

In [1124]:
features = df_train1.columns[0:-3]  # Exclude 'respondent_id', 'xyz_vaccine', 'seasonal_vaccine'
target_xyz = 'xyz_vaccine'
target_seasonal = 'seasonal_vaccine'
features

Index(['xyz_concern', 'xyz_knowledge', 'behavioral_antiviral_meds',
       'behavioral_avoidance', 'behavioral_face_mask', 'behavioral_wash_hands',
       'behavioral_large_gatherings', 'behavioral_outside_home',
       'behavioral_touch_face', 'doctor_recc_xyz', 'doctor_recc_seasonal',
       'chronic_med_condition', 'child_under_6_months', 'health_worker',
       'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_xyz_sick_from_vacc', 'opinion_seas_vacc_effective',
       'opinion_seas_risk', 'opinion_seas_sick_from_vacc', 'household_adults',
       'household_children', 'age_range_encoded', 'education_encoded',
       'race_encoded', 'sex_encoded', 'income_poverty_encoded',
       'marital_status_encoded', 'rent_or_own_encoded',
       'employment_status_encoded', 'hhs_geo_region_encoded',
       'census_msa_encoded'],
      dtype='object')

In [1126]:
X = df_train1[features]
y_xyz = df_train1[target_xyz]
y_seasonal = df_train1[target_seasonal]
X_train, X_val, y_xyz_train, y_xyz_val = train_test_split(X, y_xyz, test_size=0.2, random_state=42)
X_train, X_val, y_seasonal_train, y_seasonal_val = train_test_split(X, y_seasonal, test_size=0.2, random_state=42)
X_train_val, X_test, y_xyz_train_val, y_xyz_test = train_test_split(X, y_xyz, test_size=0.2, random_state=42)
X_train_val, X_test, y_seasonal_train_val, y_seasonal_test = train_test_split(X, y_seasonal, test_size=0.2, random_state=42)

In [1128]:
# Initialize Logistic Regression models
model_xyz = LogisticRegression(max_iter=1000, random_state=42)
model_seasonal = LogisticRegression(max_iter=1000, random_state=42)

In [1130]:
# Fit models
model_xyz.fit(X_train,y_seasonal_train)
model_seasonal.fit(X_train,y_seasonal_train )

LogisticRegression(max_iter=1000, random_state=42)

In [1132]:
# Predict probabilities for validation set
y_pred_prob_xyz = model_xyz.predict_proba(X_val)[:, 1]
y_pred_prob_seasonal = model_seasonal.predict_proba(X_val)[:, 1]

In [1134]:
# Calculate ROC AUC score for validation
roc_auc_xyz = roc_auc_score(y_xyz_val, y_pred_prob_xyz)
roc_auc_seasonal = roc_auc_score(y_seasonal_val, y_pred_prob_seasonal)
print(f"ROC AUC for xyz_vaccine: {roc_auc_xyz}")
print(f"ROC AUC for seasonal_vaccine: {roc_auc_seasonal}")

ROC AUC for xyz_vaccine: 0.7019518610964038
ROC AUC for seasonal_vaccine: 0.8491295528646494

In [1136]:
X_test

,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_xyz,...,age_range_encoded,education_encoded,race_encoded,sex_encoded,income_poverty_encoded,marital_status_encoded,rent_or_own_encoded,employment_status_encoded,hhs_geo_region_encoded,census_msa_encoded
15772,2.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0,3,0,0,1,1,0,1,4,2
9407,3.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,1,3,0,1,1,1,0,1,6,2
16515,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,2,3,0,0,1,0,0,1,4,1
23353,2.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1,3,0,0,2,1,0,1,1,0
10008,1.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,3,3,0,1,2,1,0,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25132,1.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,...,1,3,0,0,2,1,0,1,0,1
20086,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,2,2,0,1,1,0,0,1,0,1
5045,2.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,...,2,3,0,1,1,1,0,1,2,0
6340,3.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0,2,0,1,2,1,0,1,4,2
12943,3.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,1,1,0,0,1,0,0,1,6,0

In [1138]:
# Predict probabilities for test set
X_test=df12[features]
xyz_vaccine_test_probs =model_xyz.predict_proba(X_test)[:, 1]
seasonal_vaccine_test_probs = model_seasonal.predict_proba(X_test)[:, 1]

In [1140]:
df12

,respondent_id,xyz_concern,xyz_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,...,education_encoded,race_encoded,sex_encoded,income_poverty_encoded,rent_or_own_encoded,hhs_geo_region_encoded,employment_status_encoded,census_msa_encoded,marital_status_encoded,age_range_encoded
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,3.0,3,0,2.0,1.0,7,1.0,1,0.0,1
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0,1,0.0,1.0,1,1.0,0,0.0,0
2,26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,3.0,0,1,2.0,0.0,3,1.0,0,1.0,3
3,26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0,0,1.0,0.0,3,0.0,1,1.0,4
4,26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,1.0,1,0,1.0,0.0,5,1.0,0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26703,53410,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,3.0,0,0,1.0,0.0,8,1.0,2,1.0,1
26704,53411,3.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,...,1.0,0,1,0.0,1.0,2,1.0,0,1.0,0
26705,53412,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0,0,0.0,1.0,2,0.0,1,0.0,0
26706,53413,3.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,2.0,0,0,1.0,0.0,1,0.0,1,1.0,3
26707,53414,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,3.0,0,0,1.0,1.0,3,1.0,2,0.0,2

In [1142]:
submission=df12.copy()
submission['xyz_vaccine'] = xyz_vaccine_test_probs
submission['seasonal_vaccine'] = seasonal_vaccine_test_probs
submission1=submission[['respondent_id','xyz_vaccine','seasonal_vaccine']]
submission1

       respondent_id  xyz_vaccine  seasonal_vaccine
0              26707     0.231673          0.231673
1              26708     0.044317          0.044317
2              26709     0.701394          0.701394
3              26710     0.868788          0.868788
4              26711     0.520812          0.520812
...              ...          ...               ...
26703          53410     0.536320          0.536320
26704          53411     0.248943          0.248943
26705          53412     0.189620          0.189620
26706          53413     0.421227          0.421227
26707          53414     0.551772          0.551772

[26708 rows x 3 columns]

In [1144]:
submission1.to_csv('submission1.csv', index=False)